### ISSUE TITLE
low gpu/memory utilization during nn-training?

### ISSUE THREAD

**Issue by kangway** [keiserlab/e3fp#25]
@mjke @8li 
These aren't apples to apples comparisons by any means, but I wanted to get a benchmark of our neural net GPU/memory utilization. For comparison I pulled the tensorflow tutorial (I'm aware there are many differences in how tensorflow vs theano handles memory... so I'll follow up with some more direct comparisons).

Here are a couple of plots showing two different GPUs for training with e3fp (naive), the plots can be cleaned up more, but each represent 120 second windows.

![image](https://user-images.githubusercontent.com/24878745/32639284-032949fe-c578-11e7-9a1c-bdc744fcdc13.png)

![image](https://user-images.githubusercontent.com/24878745/32639293-0bd46eda-c578-11e7-896d-462302ba5f83.png)

There looks like there's a lot of deadtime.

In comparison here's the same code for monitoring the CIFAR10 dataset (locally, on my workstation):

![image](https://user-images.githubusercontent.com/24878745/32639124-32ac09ce-c577-11e7-8183-536e43d1cda0.png)

More details in these notebooks:

[1. Monitoring on mk-gpu-2 for running gpus](https://github.com/keiserlab/lab-notebook-chuang/blob/master/misc/2017-11-09%20GPU%20Monitoring%20on%20mk-gpu-2.ipynb).

[2. tensorflow CIFAR10 benchmarks run locally](https://github.com/keiserlab/lab-notebook-chuang/blob/master/misc/2017-11-09%20Useful%20Nvidia-SMI%20Queries.ipynb).

So it might not just be worth implementing in chainer, but we may need to see if there's a CPU bottleneck.

**Comment by sdaxen** [comment]
@kangway I believe you meant to post this in the @keiserlab/projects repo. This is the public repo for the E3FP codebase.

**Comment by kangway** [comment]
Oh man, my bad... thanks for pointing that out
