### ISSUE TITLE
Add examples for simple "fingerprint algebra"

### ISSUE THREAD

**Issue by sdaxen** [keiserlab/e3fp#3]
None of the existing examples explain the useful fingerprint algebra that can be done. This should be added as an example or to the README.

**Comment by sdaxen** [comment]
Also, fingerprint/database comparison examples from [e3fp.fingerprint.metrics](https://github.com/keiserlab/e3fp/tree/master/e3fp/fingerprint/metrics)

**Comment by goldnight** [comment]
Dear developpers,

I am Kinya Toda from MOLSIS Inc. in Japan. We are the distributor of MOE in Japan. One of Japanese pharmaceutical company which is our customer is interested in E3FP. In order to support our customer we tried E3FP program. Although we got the .fps file, we could not understand the .fps format. Would you let us know the deitails of .fps format? 

Many thanks,
Kinya

**Comment by sdaxen** [comment]
@goldnight, We appreciate the interest in E3FP and your question. The `.fps` file contains a [`FingerprintDatabase`](http://e3fp.readthedocs.io/en/latest/e3fp.fingerprint.html#e3fp.fingerprint.db.FingerprintDatabase) object. The `FingerprintDatabase` wraps the fingerprints stored in a SciPy sparse [`csr_matrix`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.html#scipy.sparse.csr_matrix) for efficient memory use, provides an interface to E3FP's [`Fingerprint`](http://e3fp.readthedocs.io/en/latest/e3fp.fingerprint.html#e3fp.fingerprint.fprint.Fingerprint) objects, and enables batch fingerprint manipulation.

Here is an example code snippet that loads a database, accesses its underlying array, extracts individual fingerprints, generates a copy of the database folded to a smaller number of bits, and computes pairwise Tanimoto coefficients:

```python
>>> import e3fp.fingerprint.db as db
>>> import e3fp.fingerprint.metrics as metrics
>>> fpdb = db.FingerprintDatabase.load("db_file.fps")
>>> print(fpdb)
FingerprintDatabase[name: None  fp_type: Fingerprint  level: 5  bits: 4294967296  fp_num: 3]
>>> fpdb.array
<3x4294967296 sparse matrix of type '<type 'numpy.bool_'>'
	with 135 stored elements in Compressed Sparse Row format>
>>> fpdb[0]
Fingerprint(indices=array([236364480, 285017645, 486993694, 526356276, 563733172, 714291194, 1355662222, 1377583001, 2146727905, 2219502143, 2453405156, 2523886517, 2738552880, 3079013085, 3471456286, 3560653707, 3588767207, 3654310210, 3982335018, 4222155853]), level=5, bits=4294967296, name=CHEMBL2110918-0_0)
>> fpdb["CHEMBL270807-0_0"]
[Fingerprint(indices=array([89404292, 236364480, 486993694, 526356276, 532215124, 563733172, 797308679, 848946638, 1291267363, 1439541318, 1654859292, 1748414490, 1754436793, 1806192060, 1809343852, 2033263744, 2151417394, 2257240192, 2279614144, 2294967576, 2330626290, 2420804073, 2453405156, 2738552880, 2782322589, 3493093279, 3533693651, 3560653707, 3654310210, 3871898055, 3947101849, 4072641186, 4218183267]), level=5, bits=4294967296, name=CHEMBL270807-0_0)]
>>> fpdb_folded = fpdb.fold(1024)
>>> print(fpdb_folded)
FingerprintDatabase[name: None  fp_type: Fingerprint  level: 5  bits: 1024  fp_num: 3]
>>> metrics.tanimoto(fpdb_folded)
array([[ 1.        ,  0.16216216,  0.0617284 ],
       [ 0.16216216,  1.        ,  0.08536585],
       [ 0.0617284 ,  0.08536585,  1.        ]])
```

The development version of `e3fp` uses a file format called `.fpz` that can be saved and loaded much more efficiently, which is important when the database is very large. More in-depth documentation is coming soon. In the meantime, please don't hesitate to contact us with questions.

**Comment by goldnight** [comment]
Dear Dr. Axen,

Thank you for quick response. I will try making the scripts according to your sample code.

Thanks,
Kinya
