### ISSUE TITLE
`merge_duplicate_substructs`

### ISSUE THREAD

**Issue by tentrillion** [keiserlab/e3fp#38]
Am I misunderstanding how the config parameters are supposed to work, or is this a bug?

```
from e3fp.config.params import default_params
from e3fp.pipeline import params_to_dicts
conf_params, fprint_params = params_to_dicts(default_params)
print(fprint_params)
```
This loads what I understand to be default parameters:

```
{'bits': 1024, 'level': 5, 'first': 3, 'radius_multiplier': 1.718, 'stereo': True, 'counts': False, 'include_disconnected': True, 'rdkit_invariants': False, 'merge_duplicate_substructs': True, 'exclude_floating': True}
```
Note the presence of `merge_duplicate_substructs`

When I then try to do 

```
[fprints_from_mol(mol, fprint_params=fprint_params) for mol in my_mols]
```

I get an unknown KeyError:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-2de476eee322> in <module>
      1 # for some reason this doesn't work
      2 fprint_params
----> 3 [fprints_from_mol(mol, fprint_params=fprint_params) for mol in my_mols]

<ipython-input-8-2de476eee322> in <listcomp>(.0)
      1 # for some reason this doesn't work
      2 fprint_params
----> 3 [fprints_from_mol(mol, fprint_params=fprint_params) for mol in my_mols]

~/minimamba/envs/rdkit36/lib/python3.6/site-packages/e3fp/pipeline.py in fprints_from_mol(mol, fprint_params, save)
     51 def fprints_from_mol(mol, fprint_params={}, save=False):
     52     """Generate fingerprints for all `first` conformers in mol."""
---> 53     fprints_dict = fprints_dict_from_mol(mol, save=save, **fprint_params)
     54     level = fprint_params.get("level", -1)
     55     fprints_list = fprints_from_fprints_dict(fprints_dict, level=level)

TypeError: fprints_dict_from_mol() got an unexpected keyword argument 'merge_duplicate_substructs'

```

Am I doing something wrong?  What's the intended use of the `merge_duplicate_substructure` parameter?  Should I not be using it here?  Or maybe I'm using an outdated version of the software?  When I search the GitHub repo for `merge_duplicate_substructure`, I don't see where in any of the underlying code it gets referred to.

**Comment by tentrillion** [comment]
(BTW thanks for making E3FP so easy to use and install.  It's great!)

**Comment by sethaxen** [comment]
> Am I doing something wrong? What's the intended use of the `merge_duplicate_substructure` parameter? Should I not be using it here? Or maybe I'm using an outdated version of the software? When I search the GitHub repo for `merge_duplicate_substructure`, I don't see where in any of the underlying code it gets referred to.

No, you're not doing anything wrong. This setting is a callback to an earlier version, and the current version doesn't use it. I'll submit a fix re-linking it to the fingerprinting.

The `merge_duplicate_substructs` is meant to correspond to the `remove_duplicate_substructs` keyword argument to `Fingerprinter`. For a description, I've included the relevant section from the paper and the docstring:

<img width="957" alt="Screen Shot 2020-02-24 at 5 18 49 PM" src="https://user-images.githubusercontent.com/8673634/75205879-d78f7480-5729-11ea-9cf3-b7fc5b97c21a.png">

```
    remove_duplicate_substructs : bool, optional
        If a substructure arises that corresponds to an identifier already in
        the fingerprint, then the identifier for the duplicate substructure is
        not added to fingerprint.
```


> (BTW thanks for making E3FP so easy to use and install. It's great!)

You're welcome!
