### ISSUE TITLE
Odd behaviour when adding Hs to conformers.

### ISSUE THREAD

**Issue by SOH9797** [keiserlab/e3fp#59]
This code [in Jupyter-lab]:
```
mol = confs_from_smiles('C1CCCCC1','cyclohexane',confgen_params=confgen_params)
mol = Chem.AddHs(mol)
mol
```
Appears to incorrectly align all Hs to the centre of the cyclohexane ring?!

I presume this is a bug?

**Comment by sethaxen** [comment]
As noted in the [rdkit docs](https://rdkit.org/docs/source/rdkit.Chem.rdmolops.html#rdkit.Chem.rdmolops.AddHs), by default `AddHs` does not add 3D coordinates for the hydrogens, so I believe they are all rendered at the origin when the rest of the molecular already has 3D coordinates (e.g. after conformer generation):

```python
>>> from e3fp.pipeline import confs_from_smiles
>>> import rdkit.Chem as Chem
>>> confgen_params = {'max_energy_diff': 20.0, 'first': 3}
>>> mol = confs_from_smiles('C1CCCCC1','cyclohexane',confgen_params=confgen_params)
>>> mol
```
![image](https://user-images.githubusercontent.com/8673634/171520922-ed2f6c8e-a887-4a7a-9c74-72fa6ee01a95.png)

```python
>>> mol2 = Chem.AddHs(mol)
>>> mol2
```
![image](https://user-images.githubusercontent.com/8673634/171520994-922a0d4b-8a9d-431a-b644-5acc1d83bde3.png)

You should explicitly add 3D coordinates for hydrogens:

```python
>>> mol3 = Chem.AddHs(mol, addCoords=True)
>>> mol3
```
![image](https://user-images.githubusercontent.com/8673634/171521093-e4227f2d-297b-437b-9ddf-386e47adb12e.png)

However, I'm not certain how accurate rdkit's placement of 3D coordinates of hydrogens is. Note that we add explicit hydrogens internally before conformer generation and remove them afterward. Like much of rdkit, we require hydrogens be implicit.

**Comment by SOH9797** [comment]
OK, thanks, 
I had realised that it was an RDKit issue shortly after posting.
That fix is probably good enough since I only need to add Hs for visualization.
