### ISSUE TITLE
 ImportError: No module named rdkit

### ISSUE THREAD

**Issue by sophialeeman** [keiserlab/e3fp#61]
When I run pytest on e3fp, I am getting the error:

 ImportError: No module named rdkit

However, I have installed rdkit through the pip installation described at this website: https://github.com/kuelumbus/rdkit-pypi
with the following command: 
`python3 -m pip install rdkit-pypi --user`

rdkit runs quite smoothly when I call

`python3 -c "from rdkit import Chem; print(Chem.MolToMolBlock(Chem.MolFromSmiles('C1CCC1')))"`

But it returns the same error when I call

`python -c "from rdkit import Chem; print(Chem.MolToMolBlock(Chem.MolFromSmiles('C1CCC1')))"`

I think the rdkit is not working because I have installed it in python3 instead of python or something like that but am unsure how to fix this, as when I try to install it in python:

`python -m pip install rdkit-pypi --user`

I get an error that states:

"DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
ERROR: Could not find a version that satisfies the requirement rdkit-pypi (from versions: none)
ERROR: No matching distribution found for rdkit-pypi
WARNING: You are using pip version 20.3.4; however, version 21.3.1 is available.
You should consider upgrading via the '/usr/bin/python -m pip install --upgrade pip' command."

**Comment by sophialeeman** [comment]
Update: I wrote an alias to make a call to python use the version 3.6.9 instead of the old version, and the commands
`python -m pip install rdkit-pypi --user`
and
`python -c "from rdkit import Chem; print(Chem.MolToMolBlock(Chem.MolFromSmiles('C1CCC1')))"`
now work, but I am getting the same errors when calling 
`pytest e3fp`

**Comment by sophialeeman** [comment]
I tried creating an alias:

`alias rdkit=rdkit-pypi`

But this changed nothing with the error messages.

**Comment by mjke** [comment]
hi @sophialeeman , this sounds like an environment management issue. are you using [conda](https://docs.conda.io/projects/conda/en/latest/index.html)? generally this is the easiest way to install and use this package -- e.g., "Option 1" of https://e3fp.readthedocs.io/en/latest/install.html#installation

**Comment by sophialeeman** [comment]
I was having difficulty installing conda, as I am working on a university computing machine for which I don't have access to a lot of functions. I will take this up with my university computing department.

**Comment by sophialeeman** [comment]
Thank you!
