### ISSUE TITLE
pytest failure

### ISSUE THREAD

**Issue by slchan3** [keiserlab/e3fp#70]
Perhaps it's just that the reference answer needs to be updated.

I just installed the most recent version. When I ran pytest, I got the following result, with one failure.

S.L.

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

$ pytest e3fp
============================= test session starts ==============================
platform linux -- Python 3.11.0, pytest-7.2.0, pluggy-1.0.0
rootdir: /g/gits/e3fp, configfile: pytest.ini
collected 134 items                                                            

e3fp/util.py .                                                           [  0%]
e3fp/fingerprint/db.py F.                                                [  2%]
e3fp/fingerprint/fprint.py ..                                            [  3%]
e3fp/test/test_config.py .                                               [  4%]
e3fp/test/test_conformer.py ....                                         [  7%]
e3fp/test/test_dependencies.py ..........                                [ 14%]
e3fp/test/test_fingerprint.py .........                                  [ 21%]
e3fp/test/test_fingerprinting.py ....................................... [ 50%]
........                                                                 [ 56%]
e3fp/test/test_fprint_db.py ..................                           [ 70%]
e3fp/test/test_metrics.py ............                                   [ 79%]
e3fp/test/test_struct.py ..........................                      [ 98%]
e3fp/test/test_util.py ..                                                [100%]

=================================== FAILURES ===================================
______________ [doctest] e3fp.fingerprint.db.FingerprintDatabase _______________
130     >>> from e3fp.fingerprint.metrics import tanimoto, dice, cosine
131     >>> tanimoto(db, db)
132     array([[1.        , 0.0591133 , 0.04245283],
133            [0.0591133 , 1.        , 0.0531401 ],
134            [0.04245283, 0.0531401 , 1.        ]])
135     >>> dice(db, db)
136     array([[1.        , 0.11162791, 0.08144796],
137            [0.11162791, 1.        , 0.10091743],
138            [0.08144796, 0.10091743, 1.        ]])
139     >>> cosine(db, db)
Differences (unified diff with -expected +actual):
    @@ -1,3 +1,3 @@
    -array([[1.        , 0.11163878, 0.08145547],
    -       [0.11163878, 1.        , 0.10095568],
    -       [0.08145547, 0.10095568, 1.        ]])
    +matrix([[1.        , 0.11163878, 0.08145547],
    +        [0.11163878, 1.        , 0.10095568],
    +        [0.08145547, 0.10095568, 1.        ]])

/g/gits/e3fp/e3fp/fingerprint/db.py:139: DocTestFailure
=============================== warnings summary ===============================
e3fp/fingerprint/db.py: 1 warning
e3fp/test/test_metrics.py: 32 warnings
  /home/c/Documents/SciPackages/miniconda3/envs/e3fp2/lib/python3.11/site-packages/numpy/matrixlib/defmatrix.py:69: PendingDeprecationWarning: the matrix subclass is not the recommended way to represent matrices or deal with linear algebra (see https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html). Please adjust your code to use regular ndarray.
    return matrix(data, dtype=dtype, copy=False)

e3fp/test/test_fprint_db.py::TestFingerprintDatabase::test_roundtrip
  /g/gits/e3fp/e3fp/test/test_fprint_db.py:202: E3FPDeprecationWarning: Function `save` was deprecated in 1.2 and will be removed in 1.3. Use `savez` instead.
    db.save(db_file)

e3fp/test/test_fprint_db.py::TestFingerprintDatabase::test_roundtrip2
  /g/gits/e3fp/e3fp/test/test_fprint_db.py:228: E3FPDeprecationWarning: Function `save` was deprecated in 1.2 and will be removed in 1.3. Use `savez` instead.
    db.save(db_file)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED e3fp/fingerprint/db.py::e3fp.fingerprint.db.FingerprintDatabase
================== 1 failed, 133 passed, 35 warnings in 9.98s ==================
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/c/Documents/SciPackages/miniconda3/envs/e3fp2/lib/python3.11/site-packages/standardiser/data/salts.tsv' mode='r' encoding='UTF-8'>

**Comment by sethaxen** [comment]
Thanks for the issue! This was missed because our CI wasn't testing docstrings. `soergel` was indeed returning a `matrix` when it should be returning an `ndarray`. This is fixed in #71.

**Comment by sethaxen** [comment]
You can now upgrade to the latest version with
```bash
pip install e3fp==1.2.5
```

**Comment by slchan3** [comment]
Great, thanks Seth for your quick response. Merry Christmas!
Ling
