### ISSUE TITLE
Why 26 conformations of a molecule can ultimately produce only 3 E3FP fingerprints

### ISSUE THREAD

**Issue by neo010010** [keiserlab/e3fp#75]
Hello, author.
I used the code for generating E3FP fingerprints to generate the E3FP fingerprints for the COC(=O)C(C1CCCCN1)C2=CC=CC=CC=C2 molecule in the example, and found that the 26 conformations of the molecule ended up generating only 3 E3FP fingerprints instead of the corresponding 26 E3FP fingerprints, may I ask what is the reason for this, and I have modified the fingerprint generation parameters to generate as many fingerprints as possible, please see the screenshot below for details.
![screenshot](https://github.com/user-attachments/assets/d27d9242-ab9e-4437-8634-551467bd25a6)

**Comment by sethaxen** [comment]
The default configuration only fingerprints the first 3 conformers (see https://e3fp.readthedocs.io/en/latest/usage/config.html#loading-default-parameters). Add `first: -1` to `fprint_params` to fingerprint all conformers.

**Comment by neo010010** [comment]
Problem solved, thank you very much for your help!

**Comment by sethaxen** [comment]
You're welcome!
